const {test}=require('node:test'),assert=require('node:assert/strict');const {convergences,validTicker}=require('../assets/clarity/live-market-model.js');
test('convergence counts people rather than repeated purchases',()=>{const rows=[{ticker:'T',date:'2026-09-01',type:'buy',insiderCik:'1',value:100},{ticker:'T',date:'2026-09-02',type:'buy',insiderCik:'1',value:200}];assert.equal(convergences(rows).length,0);rows.push({ticker:'T',date:'2026-09-03',type:'buy',insiderCik:'2',value:50});assert.equal(convergences(rows)[0].buyers,2);assert.equal(convergences(rows)[0].amount,350);});
test('convergence excludes unknown identities and purchases outside 30 days',()=>{const rows=[{ticker:'T',date:'2026-08-01',type:'buy',insider:'A',value:100},{ticker:'T',date:'2026-09-15',type:'buy',insider:'B',value:200},{ticker:'T',date:'2026-09-16',type:'buy',value:300}];assert.equal(convergences(rows).length,0);});
test('convergence keeps currencies separate',()=>{assert.equal(convergences([{ticker:'T',currency:'USD',date:'2026-09-01',type:'buy',insider:'A'},{ticker:'T',currency:'EUR',date:'2026-09-02',type:'buy',insider:'B'}]).length,0);});
test('all sales on the last day remain visible regardless of input ordering',()=>{const rows=[{ticker:'T',date:'2026-09-01',type:'buy',insider:'A',value:100},{ticker:'T',date:'2026-09-01',type:'buy',insider:'B',value:100},{ticker:'T',date:'2026-09-01',type:'sell',insider:'C',value:999}];assert.equal(convergences(rows)[0].sales,999);assert.equal(convergences(rows)[0].transactions.length,3);});
test('placeholder symbols cannot combine unrelated private issuers',()=>{const rows=[{ticker:'NONE',company:'Fund A',date:'2026-09-01',type:'buy',insider:'A'},{ticker:'NONE',company:'Fund B',date:'2026-09-02',type:'buy',insider:'B'}];assert.deepEqual(convergences(rows),[]);});
test('valid ticker check rejects placeholders and keeps exchange and share class suffixes',()=>{for(const value of [null,'','NONE',' none ','N/A','UNKNOWN','-','—'])assert.equal(validTicker(value),false);for(const value of ['AAPL','BRK.B','BRK-B','MC.PA','0700.HK',' sap.de '])assert.equal(validTicker(value),true);});
test('convergence groups canonical symbols and sums numeric string amounts',()=>{const rows=[{ticker:' t ',date:'2026-09-01',type:'buy',insider:'A',value:'100.5'},{ticker:'T',date:'2026-09-01',type:'buy',insider:'B',value:'200'},{ticker:'T',date:'2026-09-01',type:'sell',insider:'C',value:'50'}];const result=convergences(rows)[0];assert.equal(result.ticker,'T');assert.equal(result.amount,300.5);assert.equal(result.sales,50);});
test('missing purchase and sale amounts remain unknown while no sales means zero',()=>{for(const value of [null,undefined,'',true,'unknown']){const rows=[{ticker:'T',date:'2026-09-01',type:'buy',insider:'A',value:100},{ticker:'T',date:'2026-09-01',type:'buy',insider:'B',value}];assert.equal(convergences(rows)[0].amount,null);assert.equal(convergences(rows)[0].sales,0);rows.push({ticker:'T',date:'2026-09-01',type:'sell',insider:'C',value});assert.equal(convergences(rows)[0].sales,null);}});
