const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('assets/clarity/live-market.js','utf8'),model=require('../assets/clarity/live-market-model.js');
const day=new Date().toISOString().slice(0,10),buy={ticker:'ABC',company:'Example',type:'buy',transCode:'P',insider:'Alice',insiderCik:'1',fileDate:day,date:day,value:250,currency:'USD',url:'https://www.sec.gov/filing'};
async function mount(search='',{transactions=[buy],filings=[],activistFailure=false}={}){
 const nodes=new Map(),calls=[];function node(id){if(nodes.has(id))return nodes.get(id);const n={id,hidden:false,value:'',innerHTML:'',textContent:'',dataset:{},classList:{toggle(){}},removeAttribute(){},scrollIntoView(){},insertAdjacentHTML(_,html){this.innerHTML=html+this.innerHTML;},querySelector:s=>node(id+s),querySelectorAll:()=>[]};nodes.set(id,n);return n;}
 const document={getElementById:node,querySelectorAll:()=>[],createElement:()=>({}),head:{append(s){s.onload();}}};
 const U={lang:'en',t:(_,en)=>en,esc:s=>String(s??'').replace(/[<>&"]/g,'_'),format:n=>String(n),stockUrl:s=>'dashboard.html?symbol='+s,translate(){},showError(el,err){el.textContent=err.message;},api:async path=>{calls.push(path);if(path.startsWith('/api/13dg')){if(activistFailure)throw Error('offline');return {filings,total:2001,updatedAt:day};}return {transactions,updatedAt:day};}};
 await vm.runInNewContext(code,{window:{KairosUI:U,KairosAdapter:require('../assets/clarity/live-adapter.js'),KairosMarketLive:model,KairosInsiderTransaction:require('../assets/insider-transaction.js')},document,location:{search},history:{replaceState(){}},URL,URLSearchParams,Date,Map,Set});return {node,calls};
}
test('default purchase screener shows grouped buyers, dates and stock follow actions',async()=>{const h=await mount();assert.match(h.node('marketTitle').textContent,/Purchases/);assert.match(h.node('marketTabs').innerHTML,/view=purchases/);assert.match(h.node('marketControls').innerHTML,/value="7" selected/);assert.match(h.node('marketResults').innerHTML,/ABC/);assert.match(h.node('marketResults').innerHTML,/Stock & watchlist/);assert.match(h.node('marketResults').innerHTML,/Original filing/);assert.match(h.node('marketResults').innerHTML,/Trade date/);});
test('failed activist source is unavailable rather than a zero-result crossover',async()=>{const h=await mount('?view=activist-crossovers',{activistFailure:true});assert.match(h.node('marketResults').innerHTML,/unavailable/i);assert.doesNotMatch(h.node('marketResults').innerHTML,/No results|No crossovers/);assert.equal(h.calls.some(x=>x.includes('activistOnly=false&limit=2000')),true);});
test('crossover coverage reports capped source even if few qualifying matches are returned',async()=>{const h=await mount('?view=activist-crossovers');assert.match(h.node('marketResults').innerHTML,/2,000/);assert.match(h.node('marketResults').innerHTML,/initial|filing/i);});
test('legacy transaction deep link still displays sales and its 90-day period',async()=>{const h=await mount('?view=transactions&days=90&type=sell',{transactions:[{...buy,type:'sell',transCode:'S'}]});assert.match(h.node('marketResults').innerHTML,/Sell/);assert.match(h.node('marketControls').innerHTML,/value="90" selected/);});

test('the archive explains excluded purchases while the screener requires evidence',async()=>{
 const transactions=[{...buy,transCode:null,insider:'Legacy',insiderCik:'2'},{...buy,code:'A',transCode:null,insider:'Award recipient',insiderCik:'3'},{...buy,code:'P',form10b5One:true,insider:'Documented buyer',insiderCik:'4'}];
 const archive=await mount('?view=transactions',{transactions});
 assert.match(archive.node('marketResults').innerHTML,/Nature unverified/);assert.match(archive.node('marketResults').innerHTML,/Award/);assert.match(archive.node('marketResults').innerHTML,/excluded from purchase signals/);assert.match(archive.node('marketResults').innerHTML,/Planned purchase/);
 const screen=await mount('?view=purchases',{transactions});assert.match(screen.node('marketResults').innerHTML,/Documented buyer/);assert.doesNotMatch(screen.node('marketResults').innerHTML,/Award recipient|Legacy/);assert.match(screen.node('marketResults').innerHTML,/Which purchases qualify/);
});
test('crossover requires a valid execution in the last 30 days and never uses undated or impossible purchases',async()=>{
 const filings=[{ticker:'ABC',form:'13D',isActivist:true,isFirstFiling:true,fileDate:day,filerName:'Other Capital',filerCik:'9'}],offset=days=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
 const fresh=await mount('?view=activist-crossovers',{filings});assert.match(fresh.node('marketResults').innerHTML,/class="purchase-row"/);
 for(const extra of [{date:offset(-60)},{date:null},{date:offset(1)},{fileDate:offset(-1),date:day}]){const result=await mount('?view=activist-crossovers',{filings,transactions:[{...buy,...extra}]});assert.doesNotMatch(result.node('marketResults').innerHTML,/class="purchase-row"/);}
 const recent=await mount('?view=purchases',{transactions:[{...buy,date:offset(-60)}]});assert.match(recent.node('marketResults').innerHTML,/class="purchase-row"/);
});
