const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('assets/clarity/live-research.js','utf8');
async function mount({account=true,tickers=['AAPL','BH'],items=[],activity,historyRows=[],historyFailure=false,historyPending=false,failure=false,scoreApi}={}){
 const nodes=new Map(),calls=[],scoreCalls=[];let cleared=false;
 function node(id){if(nodes.has(id))return nodes.get(id);const n={id,hidden:false,dataset:{},innerHTML:'',textContent:'',classList:{add(){}},append(){},prepend(){},before(){},querySelector:sel=>node(sel),querySelectorAll:()=>[]};nodes.set(id,n);return n;}
 const document={body:node('body'),getElementById:node,createElement:node,querySelector:node};
 const U={lang:'en',t:(_,en)=>en,esc:s=>String(s??'').replace(/[<>&"]/g,'_'),format:n=>String(n),getAccount:async()=>account?{email:'test@example.invalid'}:null,researchHistory:async()=>{if(historyFailure)throw Error('history unavailable');if(historyPending)return new Promise(()=>{});return {load:()=>historyRows,clear(){cleared=true;}};},stockUrl:ticker=>'dashboard.html?symbol='+ticker,watchlist:async()=>({load:async()=>({tickers})}),api:async(url,options)=>{if(url==='/api/watchlist/score'){scoreCalls.push({url,options});return scoreApi?scoreApi(url,options):{ok:false,state:'unavailable'};}calls.push({url,options});if(failure)throw Error('offline');return {items,activity,updatedAt:'2026-10-08T15:00:00Z'};},login(){}};
 await vm.runInNewContext(code,{window:{KairosUI:U,KairosSignalContext:require('../assets/clarity/signal-context.js'),KairosWatchlistScores:require('../assets/clarity/watchlist-score-loader.js')},document,URL,URLSearchParams,Date,Map,Set});return {nodes,node,calls,scoreCalls};
}
test('anonymous research home displays login without accessing watchlist or loading stock analysis',async()=>{const f=await mount({account:false});assert.match(f.node('researchWatchContent').innerHTML,/Sign in/);assert.deepEqual(f.calls,[]);});
test('home uses one summary read, retains unavailable symbols and displays zero as real data',async()=>{const f=await mount({items:[{ticker:'AAPL',name:'Apple',price:123,currency:'USD',changePercent:0,score:0,quoteAt:'2026-09-23T12:00:00Z',latestInsider:null}]});assert.equal(f.calls.length,1);assert.match(f.calls[0].url,/^\/api\/watchlist\/summary\?/);assert.equal(f.calls[0].options,undefined);const html=f.node('researchWatchContent').innerHTML;assert.match(html,/123 USD/);assert.match(html,/0 %/);assert.match(html,/BH/);assert.match(html,/No available filing/);assert.match(html,/—/);});
test('empty list skips the summary and errors offer retry without fabricating prices',async()=>{const empty=await mount({tickers:[]});assert.equal(empty.calls.length,0);assert.match(empty.node('researchWatchContent').innerHTML,/empty/);const failed=await mount({failure:true});assert.match(failed.node('researchWatchContent').innerHTML,/temporarily unavailable/);assert.doesNotMatch(failed.node('researchWatchContent').innerHTML,/USD/);});
test('research watchlist explains stale prices, dated scores and unavailable analyses',async()=>{const f=await mount({items:[{ticker:'AAPL',price:123,currency:'USD',changePercent:0,quoteStatus:'stale',quoteAt:'2026-09-23T12:00:00Z',score:72,scoreStatus:'previous',scoreAt:'2026-09-22T10:00:00Z'}]});const html=f.node('researchWatchContent').innerHTML;assert.match(html,/Session change/);assert.match(html,/Last known price/);assert.match(html,/Previous score/);assert.match(html,/Sep 23, 2026/);assert.match(html,/Sep 22, 2026/);assert.match(html,/Price unavailable/);assert.doesNotMatch(html,/href="dashboard.html\?symbol=BH"[^>]*>Open analysis/);assert.match(html,/0 %/);});
test('archived scores are visibly identified with their calculation date and method caveat',async()=>{const f=await mount({tickers:['AVGO'],items:[{ticker:'AVGO',score:74,scoreStatus:'historical',scoreSource:'history',scoreAt:'2026-10-07T00:00:00.000Z'}]});const html=f.node('researchWatchContent').innerHTML;assert.match(html,/74/);assert.match(html,/Historical score/);assert.match(html,/Oct 7, 2026/);assert.match(f.node('researchFreshness').textContent,/method may differ/);assert.equal(f.calls.length,1);});
test('research fills a missing score automatically and exposes loading then the dated current result',async()=>{let finish;const f=await mount({tickers:['AVGO'],items:[{ticker:'AVGO',price:123,score:null}],scoreApi:()=>new Promise(resolve=>finish=resolve)});assert.equal(f.scoreCalls.length,1);assert.match(f.node('researchWatchContent').innerHTML,/Calculating score/);finish({ok:true,item:{ticker:'AVGO',score:75,scoreAt:'2026-10-09T12:00:00Z',scoreStatus:'available',scoreVersion:'v26'}});await new Promise(resolve=>setImmediate(resolve));const html=f.node('researchWatchContent').innerHTML;assert.match(html,/75/);assert.match(html,/Oct 9, 2026/);assert.doesNotMatch(html,/Calculating score|Open analysis/);});
test('an unverified acquisition does not become a green purchase signal',async()=>{const f=await mount({items:[{ticker:'AAPL',latestInsider:{type:'buy',purchaseSignalEligible:false,purchaseSignalStatus:'unknown',insider:'Buyer',fileDate:'2026-09-23'}},{ticker:'BH',latestInsider:{type:'buy',purchaseSignalEligible:true,purchaseSignalStatus:'eligible',purchaseSignalReason:'reported-purchase'}}]});const html=f.node('researchWatchContent').innerHTML;assert.match(html,/Acquisition to verify/);assert.match(html,/research-event positive[^>]*>Qualifying purchase/);assert.doesNotMatch(html,/positive[^>]*>Acquisition to verify/);});
test('research prioritizes personal filings and quotes before a compact history',async()=>{const f=await mount({activity:{available:true,events:[]},historyRows:[{ticker:'AAPL',name:'Apple'}]});const page=f.node('main').innerHTML;assert.ok(page.indexOf('researchActivityTitle')<page.indexOf('researchWatchTitle'));assert.ok(page.indexOf('researchWatchTitle')<page.indexOf('recentTitle'));assert.match(f.node('recentResearch').innerHTML,/research-recent-strip/);assert.match(f.node('researchActivityContent').innerHTML,/No filings/);});
test('research activity is personal, bounded, source-safe, and keeps execution separate from publication',async()=>{const event={ticker:'AAPL',id:'a',type:'buy',purchaseSignalEligible:true,purchaseSignalStatus:'eligible',purchaseSignalReason:'reported-purchase',insider:'Person',value:400,currency:'USD',fileDate:'2026-10-08',tradeDate:'2026-09-15',sourceUrl:'javascript:alert(1)'};const f=await mount({activity:{available:true,events:[event,{...event,id:'other',ticker:'MSFT'},{...event,id:'future',fileDate:'2026-10-09'}]}});const html=f.node('researchActivityContent').innerHTML;assert.match(html,/AAPL/);assert.doesNotMatch(html,/MSFT|javascript:|Oct 9/);assert.match(html,/Oct 8, 2026/);assert.match(html,/Sep 15, 2026/);assert.match(html,/400 USD/);assert.equal(f.calls.length,1);});
test('an unavailable filing feed is not shown as no activity',async()=>{const f=await mount({activity:{available:false,events:[]}});assert.match(f.node('researchActivityContent').innerHTML,/unavailable/);assert.doesNotMatch(f.node('researchActivityContent').innerHTML,/No filings/);});
test('unavailable or stalled optional history does not block personal filings and prices',async()=>{for(const state of [{historyFailure:true},{historyPending:true}]){const f=await mount({...state,items:[{ticker:'AAPL',price:123,currency:'USD'}],activity:{available:true,events:[]}});assert.equal(f.calls.length,1);assert.match(f.node('researchWatchContent').innerHTML,/123 USD/);assert.match(f.node('researchActivityContent').innerHTML,/No filings/);if(state.historyFailure)assert.match(f.node('recentResearch').innerHTML,/History is temporarily unavailable/);}});
