const {test}=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../assets/clarity/watchlist-client.js');
function setup(initial){let data={ok:true,exists:true,...initial},calls=[];return {calls,get data(){return data},client:create({api:async(path,options)=>{calls.push([path,options]);if(!options)return structuredClone(data);data={...data,...JSON.parse(options.body)};return {...data,ok:true};}})};}
test('reading and following stocks never enable notifications or request confirmation',async()=>{const s=setup({tickers:['MSFT'],emailAlerts:false,emailInsiderAlerts:false,types:{insider:false,cluster:false}});await s.client.load();assert.equal(s.calls.filter(x=>x[1]).length,0);await s.client.add('aapl');assert.deepEqual(s.data.tickers,['MSFT','AAPL']);assert.equal(s.data.emailAlerts,false);assert.equal(s.data.emailInsiderAlerts,false);assert.equal(s.data.types.insider,false);assert.equal(s.data.types.cluster,false);assert.equal(s.data.sendConfirmation,false);});
test('queued mutations preserve other tickers and notification preferences',async()=>{const s=setup({tickers:['MSFT'],emailAlerts:true,emailInsiderAlerts:true});await Promise.all([s.client.add('AAPL'),s.client.add('NVDA')]);await s.client.remove('AAPL');assert.deepEqual(s.data.tickers,['MSFT','NVDA']);assert.equal(s.data.emailInsiderAlerts,true);assert.equal(s.data.emailAlerts,true);});
test('an explicitly empty server list never revives a legacy Firebase list',async()=>{let read=0;const c=create({api:async()=>({ok:true,exists:true,tickers:[]}),readLegacy:async()=>{read++;return {tickers:['AAPL']}}});assert.deepEqual((await c.load()).tickers,[]);assert.equal(read,0);});
test('legacy-only list is read without writes or inheriting unconfirmed email consent',async()=>{let writes=0;const c=create({api:async(_p,o)=>{if(o)writes++;return {ok:true,exists:false,tickers:[]}},readLegacy:async()=>({tickers:['AAPL'],optIn:true,emailAlerts:true})});const v=await c.load();assert.deepEqual(v.tickers,['AAPL']);assert.equal(v.optIn,false);assert.equal(writes,0);});
test('failed reads do not overwrite saved lists; failed sync never updates the mirror',async()=>{let writes=0,mirrors=0;const a=create({api:async(_p,o)=>{if(o)writes++;throw Error('offline')}});await assert.rejects(a.add('AAPL'));assert.equal(writes,0);const b=create({api:async(_p,o)=>o?{ok:false}:{ok:true,tickers:['MSFT']},mirror:async()=>mirrors++});await assert.rejects(b.add('AAPL'));assert.equal(mirrors,0);});
test('only explicit activation requests the confirmation email, without enabling the daily digest',async()=>{const s=setup({tickers:['AAPL'],emailAlerts:false});await s.client.preferences({emailInsiderAlerts:true,lang:'en',types:{insider:true}},{sendConfirmation:true});assert.equal(s.data.emailInsiderAlerts,true);assert.equal(s.data.emailAlerts,false);assert.equal(s.data.sendConfirmation,true);assert.equal(s.data.lang,'en');});
