// Mapping nom de societe (uppercase) -> ticker Yahoo Finance avec suffix
// Suffixes Yahoo:
//   .PA = Euronext Paris
//   .L  = London Stock Exchange
//   .DE = Frankfurt (Xetra)
//   .AS = Amsterdam
//   .SW = Switzerland (SIX)
//   .MI = Borsa Italiana
//   .MC = Madrid
//   .ST = Stockholm (Nasdaq)
//   .OL = Oslo
//   .CO = Copenhagen
//   .HE = Helsinki
//
// Le mapping match par .toUpperCase().includes(key). Le premier match gagne.
// Important : entries triees par specificite (cles plus longues d'abord).

export const EU_YAHOO_SYMBOLS = [
  // ========== FRANCE (CAC 40 + SBF 120 + grosses caps) ==========
  { match: 'LVMH MOET HENNESSY', symbol: 'MC.PA' },
  { match: 'LVMH', symbol: 'MC.PA' },
  { match: 'TOTALENERGIES', symbol: 'TTE.PA' },
  { match: 'TOTAL ENERGIES', symbol: 'TTE.PA' },
  { match: 'BNP PARIBAS', symbol: 'BNP.PA' },
  { match: 'AIR LIQUIDE', symbol: 'AI.PA' },
  { match: 'SCHNEIDER ELECTRIC', symbol: 'SU.PA' },
  { match: 'SAINT-GOBAIN', symbol: 'SGO.PA' },
  { match: 'SAINT GOBAIN', symbol: 'SGO.PA' },
  { match: 'CREDIT AGRICOLE', symbol: 'ACA.PA' },
  { match: 'SOCIETE GENERALE', symbol: 'GLE.PA' },
  { match: 'COMPAGNIE GENERALE DES ETABLISSEMENTS MICHELIN', symbol: 'ML.PA' },
  { match: 'MICHELIN', symbol: 'ML.PA' },
  { match: 'PERNOD RICARD', symbol: 'RI.PA' },
  { match: 'L\'OREAL', symbol: 'OR.PA' },
  { match: 'LOREAL', symbol: 'OR.PA' },
  { match: 'L OREAL', symbol: 'OR.PA' },
  { match: 'PUBLICIS GROUPE', symbol: 'PUB.PA' },
  { match: 'PUBLICIS', symbol: 'PUB.PA' },
  { match: 'SANOFI', symbol: 'SAN.PA' },
  { match: 'AIRBUS', symbol: 'AIR.PA' },
  { match: 'CAPGEMINI', symbol: 'CAP.PA' },
  { match: 'RENAULT', symbol: 'RNO.PA' },
  { match: 'STELLANTIS', symbol: 'STLAP.PA' },
  { match: 'PEUGEOT', symbol: 'STLAP.PA' },  // ex-PSA → Stellantis
  { match: 'KERING', symbol: 'KER.PA' },
  { match: 'HERMES', symbol: 'RMS.PA' },
  { match: 'CARREFOUR', symbol: 'CA.PA' },
  { match: 'AXA', symbol: 'CS.PA' },
  { match: 'ENGIE', symbol: 'ENGI.PA' },
  { match: 'EDF', symbol: 'EDF.PA' },
  { match: 'ELECTRICITE DE FRANCE', symbol: 'EDF.PA' },
  { match: 'VEOLIA', symbol: 'VIE.PA' },
  { match: 'VINCI', symbol: 'DG.PA' },
  { match: 'BOUYGUES', symbol: 'EN.PA' },
  { match: 'SAFRAN', symbol: 'SAF.PA' },
  { match: 'THALES', symbol: 'HO.PA' },
  { match: 'DASSAULT SYSTEMES', symbol: 'DSY.PA' },
  { match: 'DASSAULT AVIATION', symbol: 'AM.PA' },
  { match: 'DASSAULT', symbol: 'AM.PA' },
  { match: 'LEGRAND', symbol: 'LR.PA' },
  { match: 'BUREAU VERITAS', symbol: 'BVI.PA' },
  { match: 'TELEPERFORMANCE', symbol: 'TEP.PA' },
  { match: 'WORLDLINE', symbol: 'WLN.PA' },
  { match: 'EUROFINS', symbol: 'ERF.PA' },
  { match: 'ARKEMA', symbol: 'AKE.PA' },
  { match: 'EDENRED', symbol: 'EDEN.PA' },
  { match: 'GETLINK', symbol: 'GET.PA' },
  { match: 'ICADE', symbol: 'ICAD.PA' },
  { match: 'UNIBAIL-RODAMCO-WESTFIELD', symbol: 'URW.PA' },
  { match: 'UNIBAIL', symbol: 'URW.PA' },
  { match: 'ACCOR', symbol: 'AC.PA' },
  { match: 'AIR FRANCE-KLM', symbol: 'AF.PA' },
  { match: 'AIR FRANCE', symbol: 'AF.PA' },
  { match: 'REMY COINTREAU', symbol: 'RCO.PA' },
  { match: 'VALEO', symbol: 'FR.PA' },
  { match: 'UBISOFT', symbol: 'UBI.PA' },
  { match: 'RUBIS', symbol: 'RUI.PA' },
  { match: 'CARMILA', symbol: 'CARM.PA' },
  { match: 'SCOR', symbol: 'SCR.PA' },
  { match: 'DERICHEBOURG', symbol: 'DBG.PA' },
  { match: 'VIVENDI', symbol: 'VIV.PA' },
  { match: 'ORANGE', symbol: 'ORA.PA' },
  { match: 'BOLLORE', symbol: 'BOL.PA' },
  { match: 'GROUPE BOLLORE', symbol: 'BOL.PA' },
  { match: 'SOCIETE BIC', symbol: 'BB.PA' },
  { match: 'BIC', symbol: 'BB.PA' },
  { match: 'FRANCAISE DES JEUX', symbol: 'FDJ.PA' },
  { match: 'FDJ', symbol: 'FDJ.PA' },
  { match: 'JCDECAUX', symbol: 'DEC.PA' },
  { match: 'BUREAU VALLEE', symbol: 'BVL.PA' },
  { match: 'EIFFAGE', symbol: 'FGR.PA' },
  { match: 'ATOS', symbol: 'ATO.PA' },
  { match: 'TF1', symbol: 'TFI.PA' },
  { match: 'M6', symbol: 'MMB.PA' },
  { match: 'METROPOLE TELEVISION', symbol: 'MMB.PA' },
  { match: 'IPSEN', symbol: 'IPN.PA' },
  { match: 'SOITEC', symbol: 'SOI.PA' },
  { match: 'STMICROELECTRONICS', symbol: 'STM.PA' },
  { match: 'PERNOD', symbol: 'RI.PA' },
  { match: 'BIOMERIEUX', symbol: 'BIM.PA' },
  { match: 'INNATE PHARMA', symbol: 'IPH.PA' },
  { match: 'INVENTIVA', symbol: 'IVA.PA' },
  { match: 'EXAIL TECHNOLOGIES', symbol: 'EXA.PA' },
  { match: 'EXOSENS', symbol: 'EXENS.PA' },
  { match: 'INFOTEL', symbol: 'INF.PA' },
  { match: 'ABEO', symbol: 'ABEO.PA' },
  { match: 'ABIVAX', symbol: 'ABVX.PA' },
  { match: 'ATEME', symbol: 'ATEME.PA' },
  { match: 'POULAILLON', symbol: 'ALPLN.PA' },  // Euronext Growth
  { match: 'XILAM ANIMATION', symbol: 'XIL.PA' },
  { match: 'GROUPE TERA', symbol: 'ALTER.PA' },
  { match: 'ELIOR', symbol: 'ELIOR.PA' },
  { match: 'MEDINCELL', symbol: 'MEDCL.PA' },
  { match: 'VIRIDIEN', symbol: 'VIRI.PA' },
  { match: 'AMUNDI', symbol: 'AMUN.PA' },
  { match: 'EUTELSAT', symbol: 'ETL.PA' },
  { match: 'SUEZ', symbol: 'SEV.PA' },

  // ========== UK (FTSE 100 + 250) ==========
  { match: 'BARCLAYS', symbol: 'BARC.L' },
  { match: 'HSBC', symbol: 'HSBA.L' },
  { match: 'LLOYDS BANKING', symbol: 'LLOY.L' },
  { match: 'LLOYDS', symbol: 'LLOY.L' },
  { match: 'NATWEST', symbol: 'NWG.L' },
  { match: 'STANDARD CHARTERED', symbol: 'STAN.L' },
  { match: 'BP PLC', symbol: 'BP.L' },
  { match: 'BP P.L.C', symbol: 'BP.L' },
  { match: 'SHELL', symbol: 'SHEL.L' },
  { match: 'ASTRAZENECA', symbol: 'AZN.L' },
  { match: 'GLAXOSMITHKLINE', symbol: 'GSK.L' },
  { match: 'GSK PLC', symbol: 'GSK.L' },
  { match: 'UNILEVER', symbol: 'ULVR.L' },
  { match: 'DIAGEO', symbol: 'DGE.L' },
  { match: 'TESCO', symbol: 'TSCO.L' },
  { match: 'SAINSBURYS', symbol: 'SBRY.L' },
  { match: 'NATIONAL GRID', symbol: 'NG.L' },
  { match: 'BRITISH AMERICAN TOBACCO', symbol: 'BATS.L' },
  { match: 'IMPERIAL BRANDS', symbol: 'IMB.L' },
  { match: 'RIO TINTO', symbol: 'RIO.L' },
  { match: 'ANGLO AMERICAN', symbol: 'AAL.L' },
  { match: 'GLENCORE', symbol: 'GLEN.L' },
  { match: 'BHP', symbol: 'BHP.L' },
  { match: 'VODAFONE', symbol: 'VOD.L' },
  { match: 'RECKITT BENCKISER', symbol: 'RKT.L' },
  { match: 'ROLLS-ROYCE', symbol: 'RR.L' },
  { match: 'ROLLS ROYCE', symbol: 'RR.L' },
  { match: 'BAE SYSTEMS', symbol: 'BA.L' },
  { match: 'PRUDENTIAL PLC', symbol: 'PRU.L' },
  { match: 'AVIVA', symbol: 'AV.L' },
  { match: 'LEGAL & GENERAL', symbol: 'LGEN.L' },
  { match: 'M&G PLC', symbol: 'MNG.L' },
  { match: 'SCHRODERS', symbol: 'SDR.L' },
  { match: 'ABRDN', symbol: 'ABDN.L' },
  { match: 'BURBERRY', symbol: 'BRBY.L' },
  { match: 'NEXT', symbol: 'NXT.L' },
  { match: 'WHITBREAD', symbol: 'WTB.L' },
  { match: 'BT GROUP', symbol: 'BT-A.L' },
  { match: 'OCADO', symbol: 'OCDO.L' },
  { match: 'OXFORD METRICS', symbol: 'OMG.L' },
  { match: 'BOOT (HENRY)', symbol: 'BOOT.L' },
  { match: 'BLACKROCK INCOME AND GROWTH', symbol: 'BRIG.L' },
  { match: 'STS GLOBAL INCOME', symbol: 'STS.L' },

  // ========== ALLEMAGNE (DAX 40) ==========
  { match: 'SAP SE', symbol: 'SAP.DE' },
  { match: 'SAP AG', symbol: 'SAP.DE' },
  { match: 'SIEMENS AG', symbol: 'SIE.DE' },
  { match: 'SIEMENS', symbol: 'SIE.DE' },
  { match: 'ALLIANZ', symbol: 'ALV.DE' },
  { match: 'BMW', symbol: 'BMW.DE' },
  { match: 'BAYERISCHE MOTOREN', symbol: 'BMW.DE' },
  { match: 'MERCEDES-BENZ', symbol: 'MBG.DE' },
  { match: 'MERCEDES BENZ', symbol: 'MBG.DE' },
  { match: 'VOLKSWAGEN', symbol: 'VOW3.DE' },
  { match: 'PORSCHE', symbol: 'P911.DE' },
  { match: 'BAYER AG', symbol: 'BAYN.DE' },
  { match: 'BAYER', symbol: 'BAYN.DE' },
  { match: 'BASF', symbol: 'BAS.DE' },
  { match: 'DEUTSCHE BANK', symbol: 'DBK.DE' },
  { match: 'COMMERZBANK', symbol: 'CBK.DE' },
  { match: 'DEUTSCHE TELEKOM', symbol: 'DTE.DE' },
  { match: 'DEUTSCHE POST', symbol: 'DHL.DE' },
  { match: 'DHL GROUP', symbol: 'DHL.DE' },
  { match: 'DEUTSCHE BOERSE', symbol: 'DB1.DE' },
  { match: 'ADIDAS', symbol: 'ADS.DE' },
  { match: 'PUMA', symbol: 'PUM.DE' },
  { match: 'INFINEON', symbol: 'IFX.DE' },
  { match: 'CONTINENTAL AG', symbol: 'CON.DE' },
  { match: 'CONTINENTAL', symbol: 'CON.DE' },
  { match: 'HENKEL', symbol: 'HEN3.DE' },
  { match: 'BEIERSDORF', symbol: 'BEI.DE' },
  { match: 'MUNICH RE', symbol: 'MUV2.DE' },
  { match: 'HANNOVER RUECK', symbol: 'HNR1.DE' },
  { match: 'FRESENIUS', symbol: 'FRE.DE' },
  { match: 'MERCK KGAA', symbol: 'MRK.DE' },
  { match: 'RWE', symbol: 'RWE.DE' },
  { match: 'E.ON', symbol: 'EOAN.DE' },
  { match: 'EON SE', symbol: 'EOAN.DE' },
  { match: 'BRENNTAG', symbol: 'BNR.DE' },
  { match: 'COVESTRO', symbol: '1COV.DE' },
  { match: 'SARTORIUS', symbol: 'SRT3.DE' },
  { match: 'SYMRISE', symbol: 'SY1.DE' },

  // ========== PAYS-BAS (AEX) ==========
  { match: 'ASML', symbol: 'ASML.AS' },
  { match: 'PROSUS', symbol: 'PRX.AS' },
  { match: 'ADYEN', symbol: 'ADYEN.AS' },
  { match: 'ING GROEP', symbol: 'INGA.AS' },
  { match: 'ING GROUP', symbol: 'INGA.AS' },
  { match: 'AHOLD', symbol: 'AD.AS' },
  { match: 'AHOLD DELHAIZE', symbol: 'AD.AS' },
  { match: 'HEINEKEN', symbol: 'HEIA.AS' },
  { match: 'AKZO NOBEL', symbol: 'AKZA.AS' },
  { match: 'PHILIPS', symbol: 'PHIA.AS' },
  { match: 'KPN', symbol: 'KPN.AS' },
  { match: 'NN GROUP', symbol: 'NN.AS' },
  { match: 'AEGON', symbol: 'AGN.AS' },
  { match: 'WOLTERS KLUWER', symbol: 'WKL.AS' },
  { match: 'RANDSTAD', symbol: 'RAND.AS' },
  { match: 'SIGNIFY', symbol: 'LIGHT.AS' },
  { match: 'DSM-FIRMENICH', symbol: 'DSFIR.AS' },
  { match: 'ARGENX', symbol: 'ARGX.AS' },
  { match: 'EXOR', symbol: 'EXO.AS' },
  { match: 'STELLANTIS NV', symbol: 'STLAP.PA' },
  { match: 'UNIVERSAL MUSIC', symbol: 'UMG.AS' },

  // ========== SUISSE (SMI) ==========
  { match: 'NESTLE SA', symbol: 'NESN.SW' },
  { match: 'NESTLE', symbol: 'NESN.SW' },
  { match: 'ROCHE HOLDING', symbol: 'ROG.SW' },
  { match: 'ROCHE', symbol: 'ROG.SW' },
  { match: 'NOVARTIS', symbol: 'NOVN.SW' },
  { match: 'UBS GROUP', symbol: 'UBSG.SW' },
  { match: 'CREDIT SUISSE', symbol: 'UBSG.SW' },  // merged into UBS
  { match: 'ZURICH INSURANCE', symbol: 'ZURN.SW' },
  { match: 'ABB LTD', symbol: 'ABBN.SW' },
  { match: 'ABB ', symbol: 'ABBN.SW' },
  { match: 'RICHEMONT', symbol: 'CFR.SW' },
  { match: 'SWISS RE', symbol: 'SREN.SW' },
  { match: 'SWATCH', symbol: 'UHR.SW' },
  { match: 'SIKA', symbol: 'SIKA.SW' },
  { match: 'GIVAUDAN', symbol: 'GIVN.SW' },
  { match: 'LONZA', symbol: 'LONN.SW' },
  { match: 'ALCON', symbol: 'ALC.SW' },
  { match: 'GLENCORE PLC', symbol: 'GLEN.L' },
  { match: 'PARTNERS GROUP', symbol: 'PGHN.SW' },
  { match: 'SWISSCOM', symbol: 'SCMN.SW' },
  { match: 'GEBERIT', symbol: 'GEBN.SW' },

  // ========== ITALIE (FTSE MIB) ==========
  { match: 'ENEL SPA', symbol: 'ENEL.MI' },
  { match: 'ENEL ', symbol: 'ENEL.MI' },
  { match: 'ENI SPA', symbol: 'ENI.MI' },
  { match: 'ENI ', symbol: 'ENI.MI' },
  { match: 'GENERALI', symbol: 'G.MI' },
  { match: 'INTESA SANPAOLO', symbol: 'ISP.MI' },
  { match: 'UNICREDIT', symbol: 'UCG.MI' },
  { match: 'MEDIOBANCA', symbol: 'MB.MI' },
  { match: 'TELECOM ITALIA', symbol: 'TIT.MI' },
  { match: 'FINECOBANK', symbol: 'FBK.MI' },
  { match: 'STELLANTIS NV', symbol: 'STLAM.MI' },
  { match: 'FERRARI NV', symbol: 'RACE.MI' },
  { match: 'FERRARI ', symbol: 'RACE.MI' },
  { match: 'PIRELLI', symbol: 'PIRC.MI' },
  { match: 'CAMPARI', symbol: 'CPR.MI' },
  { match: 'PRADA', symbol: 'PRG.MI' },
  { match: 'POSTE ITALIANE', symbol: 'PST.MI' },
  { match: 'SNAM', symbol: 'SRG.MI' },
  { match: 'TERNA', symbol: 'TRN.MI' },
  { match: 'ATLANTIA', symbol: 'ATL.MI' },
  { match: 'LEONARDO', symbol: 'LDO.MI' },
  { match: 'PRYSMIAN', symbol: 'PRY.MI' },
  { match: 'MONCLER', symbol: 'MONC.MI' },
  { match: 'SAIPEM', symbol: 'SPM.MI' },
  { match: 'AZIMUT', symbol: 'AZM.MI' },

  // ========== ESPAGNE (IBEX 35) ==========
  { match: 'BANCO SANTANDER', symbol: 'SAN.MC' },
  { match: 'SANTANDER', symbol: 'SAN.MC' },
  { match: 'BBVA', symbol: 'BBVA.MC' },
  { match: 'CAIXABANK', symbol: 'CABK.MC' },
  { match: 'BANKINTER', symbol: 'BKT.MC' },
  { match: 'TELEFONICA', symbol: 'TEF.MC' },
  { match: 'IBERDROLA', symbol: 'IBE.MC' },
  { match: 'REPSOL', symbol: 'REP.MC' },
  { match: 'INDITEX', symbol: 'ITX.MC' },
  { match: 'AENA', symbol: 'AENA.MC' },
  { match: 'FERROVIAL', symbol: 'FER.MC' },
  { match: 'ACS ACTIVIDADES', symbol: 'ACS.MC' },
  { match: 'NATURGY', symbol: 'NTGY.MC' },
  { match: 'ENDESA', symbol: 'ELE.MC' },
  { match: 'CELLNEX', symbol: 'CLNX.MC' },
  { match: 'AMADEUS IT', symbol: 'AMS.MC' },
  { match: 'GRIFOLS', symbol: 'GRF.MC' },
  { match: 'MERLIN PROPERTIES', symbol: 'MRL.MC' },
  { match: 'IAG', symbol: 'IAG.MC' },
  { match: 'INTERNATIONAL CONSOLIDATED AIRLINES', symbol: 'IAG.MC' },
  { match: 'ACCIONA', symbol: 'ANA.MC' },
  { match: 'MAPFRE', symbol: 'MAP.MC' },

  // ========== SUEDE (OMXS30) ==========
  { match: 'ATLAS COPCO', symbol: 'ATCO-A.ST' },
  { match: 'ASTRA ZENECA', symbol: 'AZN.L' },  // dual-listed UK
  { match: 'VOLVO AB', symbol: 'VOLV-B.ST' },
  { match: 'AB VOLVO', symbol: 'VOLV-B.ST' },
  { match: 'ERICSSON', symbol: 'ERIC-B.ST' },
  { match: 'H&M', symbol: 'HM-B.ST' },
  { match: 'HENNES & MAURITZ', symbol: 'HM-B.ST' },
  { match: 'SANDVIK', symbol: 'SAND.ST' },
  { match: 'SEB ', symbol: 'SEB-A.ST' },
  { match: 'SVENSKA HANDELSBANKEN', symbol: 'SHB-A.ST' },
  { match: 'NORDEA', symbol: 'NDA-SE.ST' },
  { match: 'TELIA COMPANY', symbol: 'TELIA.ST' },
  { match: 'INVESTOR AB', symbol: 'INVE-B.ST' },
  { match: 'ESSITY', symbol: 'ESSITY-B.ST' },
  { match: 'ASTRAZENECA AB', symbol: 'AZN.L' },
  { match: 'EVOLUTION GAMING', symbol: 'EVO.ST' },
  { match: 'BOLIDEN', symbol: 'BOL.ST' },
  { match: 'ASSA ABLOY', symbol: 'ASSA-B.ST' },
  { match: 'SKF AB', symbol: 'SKF-B.ST' },
  { match: 'ALFA LAVAL', symbol: 'ALFA.ST' },
  { match: 'EPIROC', symbol: 'EPI-A.ST' },

  // ========== NORVEGE (OBX) ==========
  { match: 'EQUINOR', symbol: 'EQNR.OL' },
  { match: 'DNB BANK', symbol: 'DNB.OL' },
  { match: 'TELENOR', symbol: 'TEL.OL' },
  { match: 'AKER BP', symbol: 'AKRBP.OL' },
  { match: 'NORSK HYDRO', symbol: 'NHY.OL' },
  { match: 'YARA INTERNATIONAL', symbol: 'YAR.OL' },
  { match: 'YARA', symbol: 'YAR.OL' },
  { match: 'STOREBRAND', symbol: 'STB.OL' },
  { match: 'ORKLA', symbol: 'ORK.OL' },
  { match: 'GJENSIDIGE', symbol: 'GJF.OL' },
  { match: 'SCHIBSTED', symbol: 'SCHA.OL' },
  { match: 'KONGSBERG', symbol: 'KOG.OL' },
  { match: 'SUBSEA 7', symbol: 'SUBC.OL' },
  { match: 'AKER SOLUTIONS', symbol: 'AKSO.OL' },
  { match: 'MOWI', symbol: 'MOWI.OL' },

  // ========== DANEMARK (OMXC25) ==========
  { match: 'NOVO NORDISK', symbol: 'NOVO-B.CO' },
  { match: 'ORSTED', symbol: 'ORSTED.CO' },
  { match: 'CARLSBERG', symbol: 'CARL-B.CO' },
  { match: 'A.P. MOLLER-MAERSK', symbol: 'MAERSK-B.CO' },
  { match: 'A P MOLLER MAERSK', symbol: 'MAERSK-B.CO' },
  { match: 'MAERSK', symbol: 'MAERSK-B.CO' },
  { match: 'VESTAS WIND', symbol: 'VWS.CO' },
  { match: 'VESTAS', symbol: 'VWS.CO' },
  { match: 'COLOPLAST', symbol: 'COLO-B.CO' },
  { match: 'GENMAB', symbol: 'GMAB.CO' },
  { match: 'DSV', symbol: 'DSV.CO' },
  { match: 'PANDORA', symbol: 'PNDORA.CO' },
  { match: 'DANSKE BANK', symbol: 'DANSKE.CO' },
  { match: 'TRYG', symbol: 'TRYG.CO' },
  { match: 'NOVOZYMES', symbol: 'NZYM-B.CO' },
  { match: 'AMBU', symbol: 'AMBU-B.CO' },

  // ========== FINLANDE (OMXH25) ==========
  { match: 'NOKIA OYJ', symbol: 'NOKIA.HE' },
  { match: 'NOKIA', symbol: 'NOKIA.HE' },
  { match: 'NESTE', symbol: 'NESTE.HE' },
  { match: 'KONE OYJ', symbol: 'KNEBV.HE' },
  { match: 'KONE ', symbol: 'KNEBV.HE' },
  { match: 'STORA ENSO', symbol: 'STERV.HE' },
  { match: 'UPM-KYMMENE', symbol: 'UPM.HE' },
  { match: 'UPM ', symbol: 'UPM.HE' },
  { match: 'WARTSILA', symbol: 'WRT1V.HE' },
  { match: 'FORTUM', symbol: 'FORTUM.HE' },
  { match: 'METSO', symbol: 'METSO.HE' },
  { match: 'OUTOKUMPU', symbol: 'OUT1V.HE' },
  { match: 'NORDEA BANK', symbol: 'NDA-FI.HE' },
  { match: 'KESKO', symbol: 'KESKOB.HE' },
  { match: 'ELISA', symbol: 'ELISA.HE' },
  { match: 'SAMPO', symbol: 'SAMPO.HE' },
];


/**
 * Look up Yahoo Finance ticker symbol for a European company.
 * @param {string} companyName - Raw company name (any case)
 * @param {string} country - ISO country code (FR, UK, DE, NL, CH, IT, ES, SE, NO, DK, FI)
 * @returns {string|null} Yahoo symbol with suffix (e.g., "MC.PA") or null if no match
 */
export function lookupEuYahooSymbol(companyName, country) {
  if (!companyName) return null;
  const upper = String(companyName).toUpperCase().trim();
  // Match in order (entries are sorted by specificity - longest first)
  for (const entry of EU_YAHOO_SYMBOLS) {
    if (upper.includes(entry.match)) return entry.symbol;
  }
  // Fallback : si rien trouvé, mais qu'on a un ticker brut fourni, ajouter le suffix par défaut du pays
  const suffixByCountry = {
    FR: '.PA', UK: '.L', DE: '.DE', NL: '.AS', CH: '.SW',
    IT: '.MI', ES: '.MC', SE: '.ST', NO: '.OL', DK: '.CO', FI: '.HE',
  };
  return null;
}
