import {test} from 'node:test';import assert from 'node:assert/strict';import {comparableHistory,readFundOwnershipHistory,validCusip} from '../src/fund-ownership-history.js';
test('Booking common shares exclude convertible debt and normalize the April 2026 split',async()=>{
 const calls=[];const env={CACHE:{get:async()=>({ticker:'BKNG',company:{name:'BOOKING HOLDINGS'},smartMoney:{topFunds:[{cik:'1'}]}})},HISTORY:{prepare(sql){return {bind(...args){calls.push(args);return {all:async()=>({results:sql.startsWith('SELECT DISTINCT')?[{cusip:'09857L108',name:'BOOKING HOLDINGS'},{cusip:'09857LAN8',name:'BOOKING HOLDINGS'}]:[{report_date:'2026-03-31',cik:'1',shares:100,name:'BOOKING HOLDINGS'},{report_date:'2026-06-30',cik:'1',shares:2450,name:'BOOKING HOLDINGS'}]})};}};}}};
 const r=await readFundOwnershipHistory(env,'BKNG',s=>s.toUpperCase().replace(' HOLDINGS',''));assert.equal(r.reason,null);assert.equal(calls[1][0],'09857L108');assert.deepEqual(r.series.map(p=>p.shares),[2500,2450]);assert.equal(r.splitAdjusted,true);assert.equal(r.adjustments[0].ratio,25);
});
test('history compares the same observed funds and never turns a missing position into zero',()=>{const result=comparableHistory([{cik:'1',report_date:'2025-12-31',shares:100},{cik:'1',report_date:'2026-03-31',shares:120},{cik:'2',report_date:'2026-03-31',shares:1000}],2);assert.equal(result.fundCount,1);assert.deepEqual(result.series.map(r=>r.shares),[100,120]);});
test('unknown and duplicate values do not create misleading trends; observed zero remains zero',()=>{assert.equal(comparableHistory([{cik:'1',report_date:'2025-12-31',shares:null},{cik:'1',report_date:'2026-03-31',shares:20}],1).series.length,0);assert.deepEqual(comparableHistory([{cik:'1',report_date:'2025-12-31',shares:0},{cik:'1',report_date:'2026-03-31',shares:20}],1).series.map(r=>r.shares),[0,20]);assert.equal(comparableHistory([{cik:'1',report_date:'2025-12-31',shares:10},{cik:'1',report_date:'2025-12-31',shares:10},{cik:'1',report_date:'2026-03-31',shares:20}],1).series.length,0);});
test('ambiguous security classes cannot be combined into one ownership history',async()=>{const env={CACHE:{get:async()=>({ticker:'XYZ',company:{name:'Example'},smartMoney:{topFunds:[{cik:'1'}]}})},HISTORY:{prepare(){return {bind(){return {all:async()=>({results:[{cusip:'037833100',name:'Example'},{cusip:'594918104',name:'Example'}]})};}};}}};assert.equal((await readFundOwnershipHistory(env,'XYZ',s=>s.toUpperCase())).reason,'ambiguous-security');});
test('invalid archive identifiers cannot be combined with valid Apple shares',()=>{assert.equal(validCusip('037833100'),true);assert.equal(validCusip('594918104'),true);assert.equal(validCusip('037833900'),false);assert.equal(validCusip('037833950'),false);});
test('verified Apple identity excludes mislabeled Nvidia identifiers and inconsistent history rows',async()=>{
 const calls=[];const env={CACHE:{get:async()=>({ticker:'AAPL',company:{name:'Apple'},smartMoney:{topFunds:[{cik:'1'}]}})},HISTORY:{prepare(sql){return {bind(...args){calls.push({sql,args});return {all:async()=>({results:sql.startsWith('SELECT DISTINCT')?[{cusip:'037833100',name:'APPLE'},{cusip:'67066G104',name:'APPLE'}]:[{report_date:'2025-12-31',cik:'1',shares:10,name:'APPLE'},{report_date:'2026-03-31',cik:'1',shares:20,name:'APPLE'},{report_date:'2026-03-31',cik:'1',shares:900,name:'NVIDIA'}]})};}};}}};
 const r=await readFundOwnershipHistory(env,'AAPL',s=>s.toUpperCase());assert.equal(calls[1].args[0],'037833100');assert.deepEqual(r.series.map(p=>p.shares),[10,20]);assert.equal(r.fundCount,1);
});
